package org.ton.mylocalton.executors.liteclient.api.block;

import com.google.gson.Gson;
import java.io.Serializable;
import java.math.BigInteger;
import java.util.List;

import com.google.gson.GsonBuilder;
import lombok.Builder;
import lombok.Getter;
import lombok.ToString;

@Builder
@ToString
@Getter
public class Transaction implements Serializable {

  String origStatus;
  String endStatus;
  String accountAddr;
  Long outMsgsCount;

  // A reference to exactly one inbound message (which must be present in
  // InMsgDescr as well) that has been processed by the transaction.
  Message inMsg;
  String prevTxHash;
  BigInteger lt;
  BigInteger prevTxLt;
  Long now;
  Value totalFees;
  String oldHash;
  String newHash;
  TransactionDescription description;
  // References to several (maybe zero) outbound messages (also present
  // in OutMsgDescr and most likely included in OutMsgQueue) that have
  // been generated by the transaction.
  private List<Message> outMsgs;

  public String toJson() {
    Gson g = new GsonBuilder().setPrettyPrinting().create();
    return g.toJson(this);
  }
}
