package org.ton.executors.liteclient.api.block;

import lombok.*;

import java.io.Serializable;
import java.util.List;

@Builder
@ToString
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class Transaction implements Serializable {

    String origStatus;
    String endStatus;
    String accountAddr;
    Long outMsgsCount;

    // A reference to exactly one inbound message (which must be present in
    // InMsgDescr as well) that has been processed by the transaction.
    Message inMsg;

    // References to several (maybe zero) outbound messages (also present
    // in OutMsgDescr and most likely included in OutMsgQueue) that have
    // been generated by the transaction.
    private List<Message> outMsgs;

    String prevTxHash;
    String lt;
    String prevTxLt;
    Long now;
    Value totalFees;
    String oldHash;
    String newHash;
    TransactionDescription description;
}
