name: Create pre-release [dev branch]

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build x86-64 mainnet
        run: |
          mkdir artifacts
          git fetch -a
          git checkout dev
          mvn clean compile package -DskipTests
          cp target/MyLocalTon.jar artifacts/MyLocalTon-x86-64.jar

      - name: Build x86-64 testnet
        run: |
          mvn clean compile package -DskipTests -Dton_branch=testnet
          cp target/MyLocalTon.jar artifacts/MyLocalTon-x86-64-testnet.jar

      - name: Build arm64-aarch64 mainnet
        run: |
          mvn clean compile package -DskipTests -Darch=-aarch64
          cp target/MyLocalTon.jar artifacts/MyLocalTon-arm64.jar

      - name: Build arm64-aarch64 testnet
        run: |
          mvn clean compile package -DskipTests -Dton_branch=testnet -Darch=-aarch64
          cp target/MyLocalTon.jar artifacts/MyLocalTon-arm64-testnet.jar

      - name: Create pre-release
        id: create_pre_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: MyLocalTon DEV v${{ github.run_number }}
          draft: true
          prerelease: true

      - name: Upload binaries to pre-release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/*.jar
          tag: v${{ github.run_number }}
          overwrite: true
          file_glob: true
